apiVersion: v1
kind: Pod

metadata:
  name: kube-proxy
  namespace: kube-system

spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google-containers/hyperkube-amd64:v1.12.10

    command:
    - /hyperkube
    - proxy
    - --config=/etc/kubernetes/proxyconfig.yaml

    securityContext:
      privileged: true

    volumeMounts:
    - mountPath: /etc/kubernetes
      name: config
      readOnly: true

  volumes:
  - name: config
    hostPath:
      path: /etc/kubernetes
