apiVersion: v1
kind: Pod

metadata:
  name: kube-scheduler
  namespace: kube-system

spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: quay.io/coreos/hyperkube:v1.10.5_coreos.0

    command:
    - /hyperkube
    - scheduler
    - --kubeconfig=/etc/kubernetes/kubeconfig.yaml

    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1

    volumeMounts:
    - mountPath: /etc/kubernetes
      name: config
      readOnly: true

  volumes:
  - name: config
    hostPath:
      path: /etc/kubernetes
