apiVersion: v1
kind: Config

current-context: local

clusters:
- name: local
  cluster:
    server: https://${apiserver}:6443
    insecure-skip-tls-verify: true
users:
- name: local
  user:
    token: ${token}
contexts:
- name: local
  context:
    cluster: local
    user: local

